module.exports = [
    {
    name:"Dark Magician",
    boxSet:"Ghosts From the Past (GFTP)",
    condition:"Near Mint",
    cardDescription:"The ultimate wizard in terms of attack and defense.",
      img:"https://product-images.tcgplayer.com/fit-in/437x437/235736.jpg",
      rarity:"Ghost Rare",
      cardType:"Dark/Spellcaster/Normal",
      price: 599.99,
      attack: 2500,
      defense: 2100,
    },
    {
        name:"Blue-Eyes White Dragon",
    boxSet:"Ghosts From the Past: The 2nd Haunting (GFP2)",
    condition:"Near Mint",
    cardDescription:"This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.",
      img:"https://product-images.tcgplayer.com/fit-in/437x437/269576.jpg",
      rarity:"Ghost Rare",
      cardType:"Light/Dragon/Normal",
      price: 154.88,
      attack: 3000,
      defense: 2500,
    },
    {
        name: "Masked HERO Dark Law",
    boxSet:"OTS Tournament Pack 1 (OPO1)",
    condition:"Near Mint",
    cardDescription:"Must be Special Summoned with \"Mask Change\" and cannot be Special Summoned by other ways. Any card sent to your opponent's Graveyard is banished instead. Once per turn, if your opponent adds a card(s) from their Deck to their hand (except during the Draw Phase or the Damage Step): You can banish 1 random card from your opponent\'s hand.",
      img:"https://product-images.tcgplayer.com/fit-in/437x437/115955.jpg",
      rarity:"Ultimate Rare",
      cardType:"Dark/Warrior/Fusion/Effect",
      price: 398.99,
      attack: 2400,
      defense: 1800,
    },
    {
        name: "Marincess Sea Horse",
    boxSet:"Rising Rampage (RIRA)",
    condition:"Near Mint",
    cardDescription:"You can Special Summon this card (from your hand) to your zone a \"Marincess\" Link Monster points to. You can only Special Summon \"Marincess Sea Horse\" once per turn this way. During your Main Phase, except the turn this card was sent to the GY: You can banish this card from your GY; Special Summon 1 WATER monster from your hand to your zone a \"Marincess\" Link Monster points to. You can only use this effect of \"Marincess Sea Horse\" once per turn.",
      img:"https://product-images.tcgplayer.com/fit-in/437x437/194848.jpg",
      rarity:"Starlight Rare",
      cardType:"Water/Cyberse/Effect",
      price: 278.00,
      attack: 1400,
      defense: 1000,
    },
    {
        name: "Duel Link Dragon, the Duel Dragon",
    boxSet:"Championship Series Prize Cards",
    condition:"Near Mint",
    cardDescription:"2+ monsters, including a Synchro Monster During the Main Phase (Quick Effect): You can banish 1 \"Power Tool\" Synchro Monster or 1 Level 7 or 8 Dragon Synchro Monster from your Extra Deck; Special Summon 1 \"Duel Dragon Token\" with the same Type, Attribute, Level, ATK and DEF that monster had in the Extra Deck. You can only use this effect of \"Duel Link Dragon, the Duel Dragon\" once per turn. While you control \"Duel Dragon Token\", your opponent\'s monsters cannot target this card for attacks, also your opponent cannot target this card with card effects.",
      img:"https://product-images.tcgplayer.com/fit-in/437x437/198236.jpg",
      rarity:"Secret Rare",
      cardType:"Dark/Link/Effect",
      price: 278.00,
      attack: 1400,
      defense: 1000,
    },
];